# Changes here will be overwritten by Copier
SelectCitation:
- AddCitationFile_flag
- AddCFFConvert_flag
SelectCodeQualityFeatures:
- AddLocalTests_flag
- SelectGitHubActions_flag
- AddLinting_flag
- AddSonarCloud_flag
- AddEditorConfig_flag
SelectCommunityFeatures:
- AddCodeConduct_flag
- AddContributing_flag
SelectDocumentationFeatures:
- AddLocalDocumentation_flag
- AddOnlineDocumentation_flag
- AddDevDoc_flag
- AddGitHubActionDocumentation_flag
SelectGitHubActions:
- AddGitHubActionBuild_flag
SelectPublishReleaseFeatures:
- SelectCitation_flag
- AddZenodo_flag
_commit: 0.6.1
_src_path: https://github.com/nlesc/python-template.git
code_of_conduct_email: thijs.vroegh@outlook.com
copyright_holder: Thijs Vroegh
email: thijs.vroegh@outlook.com
full_name: Thijs Vroegh
github_organization: ESI-FAR/co2_emission
keywords: co2 emission, forecasting
license: Apachev2
package_name: co2_emission
package_short_description: 'forecasting co2 emission in the netherlands '
template_profile: recommended
version: 0.1.0
